spring:
  application:
    name: usuarios

  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto_aeropuerto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

jwt:
  secret: 3f9a8c1e7b2d4a6f9c0e1b3d5a7f8c2e4d6b9a1c3e5f7d8b0c2a4e6f8d1b3c5